//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCuaHangThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaSP
    {
        public int MaGia { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<System.DateTime> Time_Begin { get; set; }
        public Nullable<System.DateTime> Time_End { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
