//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCuaHangThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public Nullable<System.DateTime> Time_Create { get; set; }
        public Nullable<System.DateTime> Time_Update { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<byte> isActive { get; set; }
        public Nullable<byte> isDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
