//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCuaHangThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTDH
    {
        public int MaTTDH { get; set; }
        public int MaDH { get; set; }
        public Nullable<decimal> Tong { get; set; }
        public string PTTT { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
